repos:
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        types: [shell]
        files: \.(sh|bats)$

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.9.0-1
    hooks:
      - id: shfmt
        args: [-sr, -i, '2', -w, -ci]
        types: [shell]
        files: \.(sh|bats)$

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.15.0
    hooks:
      - id: markdownlint-cli2
        types: [markdown]
